var express = require('express')
var app =express()
var cors = require('cors')
var dotenv = require('dotenv')
var Altin = require('./src/Altin')
var Dolar = require('./src/Dolar')
var Main = require('./src/Main')
dotenv.config()
app.use(cors())

app.use(`/${process.env.VERSION}/dolar`,Dolar)
app.use(`/${process.env.VERSION}/altin`,Altin)
app.use(`/${process.env.VERSION}/main`,Main)

app.listen(process.env.PORT,()=>console.log('Server Çalışıyor.'))